# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
#
# For example, if your production organisation is "my-stats-org", then use:
#
# REPOSITORY_NAME: my-stats-org/my-stats-org.github.io
#
# ****************************************************************************

name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.18
        architecture: x64
    - name: Install dependencies
      run: make install
    - name: Build the site
      run: make build.production
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        REPOSITORY_NAME: sustainabledevelopment-vu/sustainabledevelopment-vu.github.io
        ACCESS_TOKEN: ${{ secrets.token }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
