name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Set up Python 3.10.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.18
        architecture: x64
   - name: Install dependencies
     run: 
     python -m pip install --upgrade pip
     pip install -r requirements.txt
    - name: Test the site
      run: make test
      env:
        DBNAME: ${{ secrets.DBNAME }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPASS: ${{ secrets.DBPASS }}
        DBHOST: ${{ secrets.DBHOST }}
